name: flutter_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
